Sentence.create(content: "Hello my baby, hello my darling!")
Sentence.create(content: "Which way do I go to get out of here?")
Sentence.create(content: "Don't like the weather? Wait 10 minutes.")
Sentence.create(content: "She sells seashells by the seashore.")
Sentence.create(content: "There is no punctuation in this sentence")
Sentence.create(content: "There's only two songs in me and I just wrote the third")
Sentence.create(content: "Just because you're paranoid doesn't mean they aren't after you.")
Sentence.create(content: "Toto, I've a feeling we're not in Kansas anymore.")
Sentence.create(content: "Keep your friends close, but your enemies closer.")
Sentence.create(content: "I have always depended on the kindness of strangers")
Sentence.create(content: "Carpe diem. Seize the day, boys. Make your lives extraordinary")
Sentence.create(content: "To alcohol! The cause of and solution to all Of life's problems")
Sentence.create(content: "The quick brown fox jumps over the lazy dog")
Sentence.create(content: "The five boxing wizards jump quickly")
Sentence.create(content: "Pack my box with five dozen liquor jugs")
Sentence.create(content: "She wouldn't dance with another When I saw her standing there")
Sentence.create(content: "It's been a hard day's night, and I've been working like a dog")
Sentence.create(content: "Well, that'll be the day when you say goodbye")
Sentence.create(content: "with great power must also come great responsibility")
Sentence.create(content: "take 2 of these and call me in the morning")
Sentence.create(content: "Sometimes the answer finds you")
Sentence.create(content: "While wandering in the woods I saw a bear")
Sentence.create(content: "I can jump over 3 cars if I use a trampoline")
Sentence.create(content: "Swingsets are just a way to trick you into thinking you can fly.")
Sentence.create(content: "Pianos are too big and flutes are too small.")
Sentence.create(content: "The Expanse is an underrated show")
Sentence.create(content: "Never hug a gorilla unless you are sure he will hug you back.")
Sentence.create(content: "Video killed the radio star")
Sentence.create(content: "Play me a song, you're the piano man!")
Sentence.create(content: "This is sentence number 30")

User.create(username: "admin", password: "123")
User.create(username: "Kevin", password: "123")
